AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GithubToken:
    Type: String
    Description: "GitHub Token"
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: none # Native runtime does not need a handler
      Runtime: provided.al2
      CodeUri: .
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GithubToken
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '1.0'
      Architectures:
        - arm64
      MemorySize: 256
    Metadata:
      BuildMethod: makefile
