AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GithubToken:
    Type: String
    Description: "GitHub Token"
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.github.msemitkin.githubstreakwidget.lambda.LambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GithubToken
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Architectures:
        - x86_64
      MemorySize: 512
