on:
  push:
    branches:
      - actions
#      - prod
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          version: '22.3.1'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: true
      - uses: gradle/actions/setup-gradle@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sam deploy --stack-name github-streak-widget --resolve-s3 --s3-prefix github-streak-widget --region us-east-1 --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --parameter-overrides GithubToken=$GH_TOKEN

